---
language: python
python: 
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - TOX_ENV=docs

install: python setup.py develop
script: python setup.py test

notifications:
  irc:
    channels:
      - "ircs://irc.megworld.co.uk:9000#pypump"
  
