---
language: python
python: 
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV

install:
  - python setup.py develop
  - pip install -q coverage codecov
script:
  - coverage run --branch setup.py test

after_success: codecov

notifications:
  irc:
    channels:
      - "ircs://irc.megworld.co.uk:9000#pypump"
  
